export {
  createEmptyHomepageVisuals,
  createHomepageVisuals,
  DEFAULT_HOME_HERO_IMAGE_URL,
  HOMEPAGE_POPULAR_CITY_IDS,
  isHomepageCitySlug,
  isHomepagePopularCityId,
  isHomepageVisualSlot,
  resolveHomepageCityImageUrl,
  resolveHomepageHeroImageForCity,
  resolveHomepageHeroImageUrl,
  type CreateHomepageVisualsInput,
  type HomepageCityVisual,
  type HomepagePopularCityId,
  type HomepageVisuals,
  type HomepageVisualSlot,
} from "./homepage-visuals";
