import { InstitutionStatus, InstitutionType, InstitutionVerification } from "@eduatlas/domain";
import type { InstitutionSeedRecord } from "./types";

/**
 * Development institution seed dataset (≥20).
 * Realistic Turkish names — no lorem ipsum.
 */
export const INSTITUTION_SEED_DATASET: readonly InstitutionSeedRecord[] = Object.freeze([
  // ——— Colleges / özel kolej (private_school) ———
  Object.freeze({
    id: "seed_inst_ank_kolej_1",
    slug: "ankara-bilge-koleji",
    name: "Ankara Bilge Koleji",
    type: InstitutionType.PrivateSchool,
    city: "Ankara",
    cityId: "city_ankara",
    district: "Çankaya",
    districtId: "dist_cankaya",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 312 440 12 34",
      email: "info@ankarabilge.edu.tr",
      whatsappNumber: "+90 532 440 12 34",
    },
    location: {
      address: "İlkbahar Mah. 606. Cad. No:18, Çankaya / Ankara",
      locationNotes: "Çayyolu metro hattına yakın",
      latitude: 39.8862,
      longitude: 32.8114,
    },
    searchKeywords: Object.freeze(["ankara", "bilge", "kolej", "ozel okul", "cankaya"]),
    shortDescription:
      "Çankaya’da anaokulundan liseye kadar uzanan özel eğitim programları sunan bir kolej.",
    programsSummary: "İlkokul, ortaokul ve lise; STEM ve dil ağırlıklı müfredat.",
    ageOrLevelFocus: "6–18 yaş",
    websiteUrl: "https://www.ankarabilge.edu.tr",
    isPremium: true,
    qualityScore: 88,
  }),
  Object.freeze({
    id: "seed_inst_ist_kolej_1",
    slug: "kadikoy-marmara-koleji",
    name: "Kadıköy Marmara Koleji",
    type: InstitutionType.PrivateSchool,
    city: "İstanbul",
    cityId: "city_istanbul",
    district: "Kadıköy",
    districtId: "dist_kadikoy",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 216 330 45 67",
      email: "iletisim@marmarakoleji.k12.tr",
    },
    location: {
      address: "Caferağa Mah. Moda Cad. No:42, Kadıköy / İstanbul",
      latitude: 40.9847,
      longitude: 29.0252,
    },
    searchKeywords: Object.freeze(["istanbul", "kadikoy", "marmara", "kolej", "ozel okul"]),
    shortDescription:
      "Kadıköy’de çift dilli eğitim ve güçlü rehberlik desteğiyle bilinen özel kolej.",
    programsSummary: "İlkokul–lise; İngilizce ve Almanca seçmeli programlar.",
    ageOrLevelFocus: "6–18 yaş",
    websiteUrl: "https://www.marmarakoleji.k12.tr",
    isPremium: true,
    qualityScore: 91,
  }),
  Object.freeze({
    id: "seed_inst_izm_kolej_1",
    slug: "izmir-ege-yildizlari-koleji",
    name: "İzmir Ege Yıldızları Koleji",
    type: InstitutionType.PrivateSchool,
    city: "İzmir",
    cityId: "city_izmir",
    district: "Karşıyaka",
    districtId: "dist_karsiyaka",
    verification: InstitutionVerification.Pending,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 232 365 78 90",
      email: "info@egeyildizlari.edu.tr",
    },
    location: {
      address: "Bostanlı Mah. Cemal Gürsel Cad. No:120, Karşıyaka / İzmir",
      latitude: 38.4612,
      longitude: 27.0984,
    },
    searchKeywords: Object.freeze(["izmir", "karsiyaka", "ege", "kolej", "ozel okul"]),
    shortDescription: "Karşıyaka’da sanat ve spor kulüpleriyle öne çıkan özel eğitim kurumu.",
    programsSummary: "İlkokul ve ortaokul; müzik ve yüzme kulüpleri.",
    ageOrLevelFocus: "6–14 yaş",
    qualityScore: 76,
  }),
  Object.freeze({
    id: "seed_inst_bur_kolej_1",
    slug: "bursa-nilufer-ufuk-koleji",
    name: "Bursa Nilüfer Ufuk Koleji",
    type: InstitutionType.PrivateSchool,
    city: "Bursa",
    cityId: "city_bursa",
    district: "Nilüfer",
    districtId: "dist_nilufer",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 224 441 23 45",
      email: "kayit@ufukkoleji.com.tr",
    },
    location: {
      address: "Özlüce Mah. Atatürk Cad. No:55, Nilüfer / Bursa",
      latitude: 40.2115,
      longitude: 28.9784,
    },
    searchKeywords: Object.freeze(["bursa", "nilufer", "ufuk", "kolej", "ozel okul"]),
    shortDescription: "Nilüfer’de laboratuvar ve kütüphane olanaklarıyla desteklenen özel kolej.",
    programsSummary: "İlkokul–lise; fen ve matematik atölyeleri.",
    ageOrLevelFocus: "6–18 yaş",
    qualityScore: 84,
  }),
  Object.freeze({
    id: "seed_inst_kon_kolej_1",
    slug: "konya-selcuklu-mevlana-koleji",
    name: "Konya Selçuklu Mevlana Koleji",
    type: InstitutionType.PrivateSchool,
    city: "Konya",
    cityId: "city_konya",
    district: "Selçuklu",
    districtId: "dist_selcuklu",
    verification: InstitutionVerification.Unclaimed,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 332 235 67 89",
      email: "info@mevlanakoleji.k12.tr",
    },
    location: {
      address: "Yazır Mah. Yeni İstanbul Cad. No:88, Selçuklu / Konya",
      latitude: 37.9386,
      longitude: 32.5084,
    },
    searchKeywords: Object.freeze(["konya", "selcuklu", "mevlana", "kolej", "ozel okul"]),
    shortDescription:
      "Selçuklu’da değerler eğitimi ve akademik başarıyı birlikte hedefleyen kolej.",
    programsSummary: "İlkokul ve ortaokul; hafızlık destek programı seçmeli.",
    ageOrLevelFocus: "6–14 yaş",
    qualityScore: 72,
  }),

  // ——— Kindergartens ———
  Object.freeze({
    id: "seed_inst_ist_anaokulu_1",
    slug: "besiktas-minik-adimlar-anaokulu",
    name: "Beşiktaş Minik Adımlar Anaokulu",
    type: InstitutionType.Kindergarten,
    city: "İstanbul",
    cityId: "city_istanbul",
    district: "Beşiktaş",
    districtId: "dist_besiktas",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 212 259 34 56",
      email: "merhaba@minikadimlar.com",
      whatsappNumber: "+90 533 259 34 56",
    },
    location: {
      address: "Levazım Mah. Koru Sok. No:7, Beşiktaş / İstanbul",
      locationNotes: "Levent’e yakın kapalı otopark mevcut",
      latitude: 41.0724,
      longitude: 29.0158,
    },
    searchKeywords: Object.freeze([
      "istanbul",
      "besiktas",
      "anaokulu",
      "minik adimlar",
      "okul oncesi",
    ]),
    shortDescription:
      "Beşiktaş’ta oyun temelli öğrenme ve güvenli bahçe alanıyla bilinen anaokulu.",
    programsSummary: "Tam gün ve yarım gün programları; İngilizce etkinlik saatleri.",
    ageOrLevelFocus: "24–72 ay",
    websiteUrl: "https://www.minikadimlar.com",
    isPremium: true,
    qualityScore: 90,
  }),
  Object.freeze({
    id: "seed_inst_ank_anaokulu_1",
    slug: "cankaya-golgesi-anaokulu",
    name: "Çankaya Güneşli Bahçe Anaokulu",
    type: InstitutionType.Kindergarten,
    city: "Ankara",
    cityId: "city_ankara",
    district: "Çankaya",
    districtId: "dist_cankaya",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 312 468 90 12",
      email: "info@guneslibahce.com.tr",
    },
    location: {
      address: "Aşağı Ayrancı Mah. 8. Cad. No:14, Çankaya / Ankara",
      latitude: 39.9021,
      longitude: 32.8547,
    },
    searchKeywords: Object.freeze(["ankara", "cankaya", "anaokulu", "gunesli bahce"]),
    shortDescription: "Ayrancı’da doğa pedagojisi yaklaşımıyla çalışan butik anaokulu.",
    programsSummary: "Açık hava etkinlikleri, sanat atölyesi, uyku saati düzeni.",
    ageOrLevelFocus: "2–6 yaş",
    qualityScore: 85,
  }),
  Object.freeze({
    id: "seed_inst_izm_anaokulu_1",
    slug: "bornova-mavi-kelebek-anaokulu",
    name: "Bornova Mavi Kelebek Anaokulu",
    type: InstitutionType.Kindergarten,
    city: "İzmir",
    cityId: "city_izmir",
    district: "Bornova",
    districtId: "dist_bornova",
    verification: InstitutionVerification.Unclaimed,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 232 342 11 22",
      email: "kayit@mavikelebek.okul.tr",
    },
    location: {
      address: "Erzene Mah. Ankara Cad. No:210, Bornova / İzmir",
      latitude: 38.4698,
      longitude: 27.2206,
    },
    searchKeywords: Object.freeze(["izmir", "bornova", "anaokulu", "mavi kelebek"]),
    shortDescription: "Bornova’da Montessori esintili sınıflar ve aile katılım etkinlikleri sunar.",
    programsSummary: "Yaş gruplarına göre sınıflar; haftalık aile bülteni.",
    ageOrLevelFocus: "3–6 yaş",
    qualityScore: 74,
  }),
  Object.freeze({
    id: "seed_inst_bur_anaokulu_1",
    slug: "osmangazi-mutlu-cocuklar-anaokulu",
    name: "Osmangazi Mutlu Çocuklar Anaokulu",
    type: InstitutionType.Kindergarten,
    city: "Bursa",
    cityId: "city_bursa",
    district: "Osmangazi",
    districtId: "dist_osmangazi",
    verification: InstitutionVerification.Pending,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 224 234 56 78",
      email: "info@mutlucocuklaranaokulu.com",
    },
    location: {
      address: "Çekirge Mah. 1. Murat Cad. No:33, Osmangazi / Bursa",
      latitude: 40.1987,
      longitude: 29.0392,
    },
    searchKeywords: Object.freeze(["bursa", "osmangazi", "anaokulu", "mutlu cocuklar"]),
    shortDescription: "Osmangazi’de küçük sınıf mevcutlarıyla birebir ilgiye önem veren anaokulu.",
    programsSummary: "Yemekli tam gün; drama ve ritim etkinlikleri.",
    ageOrLevelFocus: "24–66 ay",
    qualityScore: 79,
  }),
  Object.freeze({
    id: "seed_inst_kon_anaokulu_1",
    slug: "meram-nilufer-anaokulu",
    name: "Meram Nilüfer Anaokulu",
    type: InstitutionType.Kindergarten,
    city: "Konya",
    cityId: "city_konya",
    district: "Meram",
    districtId: "dist_meram",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 332 321 45 67",
      email: "meram@niluferanaokulu.com.tr",
    },
    location: {
      address: "Havzan Mah. Yeni Meram Cad. No:64, Meram / Konya",
      latitude: 37.8564,
      longitude: 32.4451,
    },
    searchKeywords: Object.freeze(["konya", "meram", "anaokulu", "nilufer"]),
    shortDescription:
      "Meram’da bahçeli kampüs ve sağlıklı beslenme menüsüyle hizmet veren anaokulu.",
    programsSummary: "Tam gün program; diyetisyen onaylı menü.",
    ageOrLevelFocus: "2–6 yaş",
    qualityScore: 82,
  }),

  // ——— Language schools ———
  Object.freeze({
    id: "seed_inst_ist_dil_1",
    slug: "sisli-global-english-academy",
    name: "Şişli Global English Academy",
    type: InstitutionType.LanguageSchool,
    city: "İstanbul",
    cityId: "city_istanbul",
    district: "Şişli",
    districtId: "dist_sisli",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 212 231 88 99",
      email: "hello@globalenglish.academy",
      whatsappNumber: "+90 555 231 88 99",
    },
    location: {
      address: "Halaskargazi Cad. No:156 Kat:3, Şişli / İstanbul",
      latitude: 41.0526,
      longitude: 28.9871,
    },
    searchKeywords: Object.freeze([
      "istanbul",
      "sisli",
      "dil okulu",
      "ingilizce",
      "global english",
    ]),
    shortDescription: "Şişli’de genel İngilizce, IELTS ve iş İngilizcesi kursları sunan dil okulu.",
    programsSummary: "A1–C1 seviyeleri; hafta içi ve hafta sonu grupları.",
    ageOrLevelFocus: "Genel İngilizce, IELTS",
    websiteUrl: "https://www.globalenglish.academy",
    isPremium: true,
    qualityScore: 87,
  }),
  Object.freeze({
    id: "seed_inst_ank_dil_1",
    slug: "ankara-kecioren-dil-atlasi",
    name: "Keçiören Dil Atlası",
    type: InstitutionType.LanguageSchool,
    city: "Ankara",
    cityId: "city_ankara",
    district: "Keçiören",
    districtId: "dist_kecioren",
    verification: InstitutionVerification.Unclaimed,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 312 357 22 11",
      email: "kayit@dilatlasi.com",
    },
    location: {
      address: "Etlik Mah. Yunus Emre Cad. No:27, Keçiören / Ankara",
      latitude: 39.9784,
      longitude: 32.8312,
    },
    searchKeywords: Object.freeze(["ankara", "kecioren", "dil okulu", "almanca", "ingilizce"]),
    shortDescription: "Keçiören’de İngilizce ve Almanca odaklı, sınav hazırlık destekli dil kursu.",
    programsSummary: "YDS/YÖKDİL hazırlık; konuşma kulüpleri.",
    ageOrLevelFocus: "Genç ve yetişkin",
    qualityScore: 71,
  }),
  Object.freeze({
    id: "seed_inst_izm_dil_1",
    slug: "konak-ege-dil-merkezi",
    name: "Konak Ege Dil Merkezi",
    type: InstitutionType.LanguageSchool,
    city: "İzmir",
    cityId: "city_izmir",
    district: "Konak",
    districtId: "dist_konak",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 232 441 33 44",
      email: "info@egedilmerkezi.com.tr",
    },
    location: {
      address: "Alsancak Mah. Kıbrıs Şehitleri Cad. No:89, Konak / İzmir",
      latitude: 38.4361,
      longitude: 27.1428,
    },
    searchKeywords: Object.freeze(["izmir", "konak", "alsancak", "dil okulu", "ege"]),
    shortDescription: "Alsancak’ta yüz yüze ve hibrit dil eğitimi veren köklü dil merkezi.",
    programsSummary: "İngilizce, İspanyolca; corporate eğitim paketleri.",
    ageOrLevelFocus: "Yetişkin ve kurumsal",
    qualityScore: 83,
  }),
  Object.freeze({
    id: "seed_inst_bur_dil_1",
    slug: "nilufer-polyglot-dil-okulu",
    name: "Nilüfer Polyglot Dil Okulu",
    type: InstitutionType.LanguageSchool,
    city: "Bursa",
    cityId: "city_bursa",
    district: "Nilüfer",
    districtId: "dist_nilufer",
    verification: InstitutionVerification.Pending,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 224 453 67 80",
      email: "merhaba@polyglotbursa.com",
    },
    location: {
      address: "İhsaniye Mah. Fsm Bulvarı No:12, Nilüfer / Bursa",
      latitude: 40.2203,
      longitude: 28.9867,
    },
    searchKeywords: Object.freeze(["bursa", "nilufer", "dil okulu", "polyglot", "ingilizce"]),
    shortDescription: "Nilüfer’de çocuk ve yetişkin gruplarıyla çalışan çok dilli dil okulu.",
    programsSummary: "Kids English, general English, TOEFL hazırlık.",
    ageOrLevelFocus: "7+ yaş ve yetişkin",
    qualityScore: 77,
  }),

  // ——— Study centers (etüt) ———
  Object.freeze({
    id: "seed_inst_ist_etut_1",
    slug: "uskudar-basari-etut-merkezi",
    name: "Üsküdar Başarı Etüt Merkezi",
    type: InstitutionType.EtutMerkezi,
    city: "İstanbul",
    cityId: "city_istanbul",
    district: "Üsküdar",
    districtId: "dist_uskudar",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 216 334 21 43",
      email: "info@basarietut.com",
    },
    location: {
      address: "Altunizade Mah. Kısıklı Cad. No:31, Üsküdar / İstanbul",
      latitude: 41.0218,
      longitude: 29.0456,
    },
    searchKeywords: Object.freeze(["istanbul", "uskudar", "etut", "lgs", "basari"]),
    shortDescription: "Üsküdar’da LGS odaklı küçük grup etütleri ve deneme sınavları düzenler.",
    programsSummary: "Matematik, fen, Türkçe etütleri; haftalık deneme.",
    ageOrLevelFocus: "Ortaokul / LGS",
    qualityScore: 86,
  }),
  Object.freeze({
    id: "seed_inst_ank_etut_1",
    slug: "yenimahalle-hedef-etut",
    name: "Yenimahalle Hedef Etüt",
    type: InstitutionType.EtutMerkezi,
    city: "Ankara",
    cityId: "city_ankara",
    district: "Yenimahalle",
    districtId: "dist_yenimahalle",
    verification: InstitutionVerification.Unclaimed,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 312 315 44 55",
      email: "kayit@hedefetut.com.tr",
    },
    location: {
      address: "Ragıp Tüzün Cad. No:78, Yenimahalle / Ankara",
      latitude: 39.9662,
      longitude: 32.7981,
    },
    searchKeywords: Object.freeze(["ankara", "yenimahalle", "etut", "yks", "hedef"]),
    shortDescription: "Yenimahalle’de YKS sayısal ve sözel branş etütleri sunan çalışma merkezi.",
    programsSummary: "TYT–AYT konu anlatımı ve soru çözümü.",
    ageOrLevelFocus: "Lise / YKS",
    qualityScore: 73,
  }),
  Object.freeze({
    id: "seed_inst_izm_etut_1",
    slug: "karsiyaka-akil-kupu-etut",
    name: "Karşıyaka Akıl Küpü Etüt",
    type: InstitutionType.EtutMerkezi,
    city: "İzmir",
    cityId: "city_izmir",
    district: "Karşıyaka",
    districtId: "dist_karsiyaka",
    verification: InstitutionVerification.Verified,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 232 381 90 01",
      email: "info@akilkupu.com",
      whatsappNumber: "+90 532 381 90 01",
    },
    location: {
      address: "Donanmacı Mah. Girne Bulvarı No:204, Karşıyaka / İzmir",
      latitude: 38.4589,
      longitude: 27.1112,
    },
    searchKeywords: Object.freeze(["izmir", "karsiyaka", "etut", "akil kupu", "lgs"]),
    shortDescription: "Karşıyaka’da bire bir ders ve ödev takip sistemiyle çalışan etüt merkezi.",
    programsSummary: "İlkokul destek + ortaokul LGS paketleri.",
    ageOrLevelFocus: "İlkokul–ortaokul",
    qualityScore: 81,
  }),
  Object.freeze({
    id: "seed_inst_kon_etut_1",
    slug: "selcuklu-zirve-etut-merkezi",
    name: "Selçuklu Zirve Etüt Merkezi",
    type: InstitutionType.EtutMerkezi,
    city: "Konya",
    cityId: "city_konya",
    district: "Selçuklu",
    districtId: "dist_selcuklu",
    verification: InstitutionVerification.Pending,
    status: InstitutionStatus.Published,
    published: true,
    contact: {
      phone: "+90 332 248 12 13",
      email: "zirve@selcukluetut.com",
    },
    location: {
      address: "Bosna Hersek Mah. Sille Cad. No:45, Selçuklu / Konya",
      latitude: 37.9214,
      longitude: 32.4922,
    },
    searchKeywords: Object.freeze(["konya", "selcuklu", "etut", "zirve", "yks"]),
    shortDescription: "Selçuklu’da deneme analizi ve rehberlik desteğiyle YKS hazırlık etütleri.",
    programsSummary: "Branş etütleri, motivasyon seminerleri.",
    ageOrLevelFocus: "Lise / YKS",
    qualityScore: 75,
  }),

  // ——— Universities (future vertical flag) ———
  Object.freeze({
    id: "seed_inst_ank_uni_1",
    slug: "ankara-teknik-universitesi",
    name: "Ankara Teknik Üniversitesi",
    type: "university",
    city: "Ankara",
    cityId: "city_ankara",
    district: "Yenimahalle",
    districtId: "dist_yenimahalle",
    verification: InstitutionVerification.Unclaimed,
    status: InstitutionStatus.Draft,
    published: false,
    futureUniversity: true,
    contact: {
      phone: "+90 312 210 10 00",
      email: "ogrenci.isleri@ankarateknik.edu.tr",
    },
    location: {
      address: "Üniversiteler Mah. Bilim Cad. No:1, Yenimahalle / Ankara",
      latitude: 39.8912,
      longitude: 32.7845,
    },
    searchKeywords: Object.freeze(["ankara", "universite", "teknik", "muhendislik", "yenimahalle"]),
    shortDescription:
      "Ankara’da mühendislik ve temel bilimler odaklı devlet üniversitesi (gelecek dikey).",
    programsSummary: "Mühendislik, fen-edebiyat ve bilgisayar bilimleri fakülteleri.",
    ageOrLevelFocus: "Lisans / yüksek lisans",
    websiteUrl: "https://www.ankarateknik.edu.tr",
    qualityScore: 0,
  }),
  Object.freeze({
    id: "seed_inst_ist_uni_1",
    slug: "istanbul-bogazici-kamu-universitesi",
    name: "İstanbul Boğaziçi Kamu Üniversitesi",
    type: "university",
    city: "İstanbul",
    cityId: "city_istanbul",
    district: "Beşiktaş",
    districtId: "dist_besiktas",
    verification: InstitutionVerification.Unclaimed,
    status: InstitutionStatus.Draft,
    published: false,
    futureUniversity: true,
    contact: {
      phone: "+90 212 359 54 00",
      email: "info@bogazicikamu.edu.tr",
    },
    location: {
      address: "Bebek Mah. Üniversite Cad. No:2, Beşiktaş / İstanbul",
      latitude: 41.0845,
      longitude: 29.0431,
    },
    searchKeywords: Object.freeze(["istanbul", "universite", "besiktas", "bogazici", "lisans"]),
    shortDescription:
      "Beşiktaş’ta sosyal ve fen bilimleri programlarıyla bilinen üniversite (gelecek dikey).",
    programsSummary: "İktisat, işletme, bilgisayar mühendisliği, psikoloji.",
    ageOrLevelFocus: "Lisans",
    qualityScore: 0,
  }),
  Object.freeze({
    id: "seed_inst_izm_uni_1",
    slug: "izmir-ege-kampus-universitesi",
    name: "İzmir Ege Kampüs Üniversitesi",
    type: "university",
    city: "İzmir",
    cityId: "city_izmir",
    district: "Bornova",
    districtId: "dist_bornova",
    verification: InstitutionVerification.Unclaimed,
    status: InstitutionStatus.Draft,
    published: false,
    futureUniversity: true,
    contact: {
      phone: "+90 232 311 10 10",
      email: "ogrenci@egekampus.edu.tr",
    },
    location: {
      address: "Kazımdirik Mah. Üniversite Cad. No:5, Bornova / İzmir",
      latitude: 38.4647,
      longitude: 27.2219,
    },
    searchKeywords: Object.freeze(["izmir", "bornova", "universite", "ege", "kampus"]),
    shortDescription:
      "Bornova kampüsünde sağlık ve mühendislik ağırlıklı üniversite (gelecek dikey).",
    programsSummary: "Tıp, diş hekimliği, mühendislik fakülteleri.",
    ageOrLevelFocus: "Lisans / tıp",
    qualityScore: 0,
  }),
]);
