export { escapeAttribute, escapeHtml } from "./escape";
export { renderMailLayout, type MailLayoutSlots } from "./layout";
export {
  renderMailDocument,
  type MailDocumentInput,
  type MailDocumentResult,
} from "./render";
export { mailTheme, type MailTheme } from "./theme";
export {
  renderMailBadge,
  renderMailBodyBlock,
  renderMailCard,
  renderMailDivider,
  renderMailFeatureList,
  renderMailFooter,
  renderMailHeader,
  renderMailHero,
  renderMailInfoBox,
  renderMailLegalFooter,
  renderMailLogo,
  renderMailPrimaryCta,
  renderMailSecondaryCta,
  renderMailSection,
  renderMailSocialLinks,
  renderMailStatsRow,
  renderMailStepsBox,
  renderMailSubtitle,
  renderMailSuccessBox,
  renderMailTitle,
  renderMailWarningBox,
  MAIL_LOGO_PATH,
  resolveMailLogoUrl,
  type MailFeatureItem,
  type MailFeatureListOptions,
  type MailFooterOptions,
  type MailHeaderOptions,
  type MailHeroOptions,
  type MailLegalFooterOptions,
  type MailLogoOptions,
  type MailPrimaryCtaOptions,
  type MailSecondaryCtaOptions,
  type MailSocialLink,
  type MailStatItem,
  type MailStepItem,
  type MailStepsBoxOptions,
} from "./components";
