/**
 * Application layer — use cases and ports.
 */

export type {
  AcquisitionCountBucket,
  AcquisitionDuplicateCandidate,
  AcquisitionInstitutionRow,
  AcquisitionOwnershipFilter,
  AcquisitionQualityDistribution,
  AcquisitionQualitySort,
  AcquisitionQueueId,
  AcquisitionStatistics,
  GetInstitutionAcquisitionDashboardDependencies,
  GetInstitutionAcquisitionDashboardInput,
  InstitutionAcquisitionDashboard,
  InstitutionQualityIndicators,
} from "./acquisition";
export {
  buildInstitutionQualityIndicators,
  getInstitutionAcquisitionDashboard,
} from "./acquisition";
export {
  type AgentIntegrationRoute,
  type AiWorkforceFoundationSummary,
  type AiWorkforceOrchestrator,
  createAiWorkforceOrchestrator,
  DISCOVERY_AGENT_CONTRACT,
  ENRICHMENT_AGENT_CONTRACT,
  FOUNDATION_AGENT_CONTRACTS,
  getAgentContract,
  listAgentIntegrationRoutes,
  type ProposeAgentArtifactInput,
  proposeAgentArtifact,
  QUALITY_AGENT_CONTRACT,
  SALES_AGENT_CONTRACT,
  summarizeAiWorkforceFoundation,
  VALIDATION_AGENT_CONTRACT,
} from "./ai-workforce";
export {
  ClaimInstitutionNotFoundError,
  ClaimRateLimitedError,
  type ClaimInviteTokenRepository,
  type ClaimRequestRepository,
  type ListRecentClaimRequestsOptions,
  ClaimSpamRejectedError,
  ClaimValidationError,
  type ApproveClaimRequestDependencies,
  type ApproveClaimRequestInput,
  type ApproveClaimRequestResult,
  approveClaimRequest,
  createInMemoryClaimInviteTokenRepository,
  InMemoryClaimInviteTokenRepository,
  isClaimRateLimited,
  isClaimRateLimitedError,
  isClaimSpamRejectedError,
  isClaimSpamSubmission,
  isClaimValidationError,
  type ResolveClaimInviteTokenResult,
  resolveClaimInviteToken,
  type SubmitClaimRequestDependencies,
  type SubmitClaimRequestInput,
  type SubmitClaimRequestResult,
  submitClaimRequest,
} from "./claims";
export type {
  EducationCatalogListOptions,
  EducationCatalogRepository,
  EducationCatalogSummary,
  GetEducationCatalogItemByIdInput,
  GetEducationCatalogItemBySlugInput,
  GetEducationCatalogSummaryDependencies,
  ListEducationCatalogItemsDependencies,
  ListEducationCatalogItemsInput,
} from "./education-catalog";
export {
  getEducationCatalogItemById,
  getEducationCatalogItemBySlug,
  getEducationCatalogSummary,
  listEducationCatalogItems,
} from "./education-catalog";
export type {
  BuildGeographyStatisticsPlaceholderInput,
  CityListOptions,
  CityRepository,
  DistrictListOptions,
  DistrictRepository,
  GeographyCatalogSummary,
  GeographyStatisticsPlaceholder,
  GetGeographyCatalogSummaryDependencies,
  ListCitiesDependencies,
  ListCitiesInput,
  ListDistrictsDependencies,
  ListDistrictsInput,
} from "./geography";
export {
  buildGeographyStatisticsPlaceholder,
  getGeographyCatalogSummary,
  listCities,
  listDistricts,
} from "./geography";
export {
  AuthenticationError,
  type AuthenticationService,
  assertPasswordPolicy,
  type CreateSessionFromIdTokenInput,
  createInMemoryAuthenticationService,
  createInMemoryOwnerBindingRepository,
  EmailAlreadyInUseError,
  EmailNotVerifiedError,
  InMemoryAuthenticationService,
  type InMemoryAuthenticationServiceOptions,
  InMemoryOwnerBindingRepository,
  InvalidCredentialsError,
  isAuthenticationError,
  isEmailAlreadyInUseError,
  isEmailNotVerifiedError,
  isInvalidCredentialsError,
  isSessionExpiredError,
  isUnauthorizedError,
  isValidEmailFormat,
  isWeakPasswordError,
  MIN_PASSWORD_LENGTH,
  normalizeEmail,
  type ChangeOwnerPasswordInput,
  type OwnerAccountProvisioner,
  type OwnerBindingRepository,
  type ProvisionOwnerAccountInput,
  type ProvisionOwnerAccountResult,
  generateTemporaryOwnerPassword,
  type RequestPasswordResetInput,
  type ResolveOwnerInstitutionDependencies,
  type ResolveOwnerInstitutionInput,
  type ResolveOwnerInstitutionResult,
  requestPasswordReset,
  resolveOwnerInstitutionId,
  revokeSession,
  type SendEmailVerificationInput,
  SessionExpiredError,
  type SignInDependencies,
  type SignInResult,
  type SignInWithEmailPasswordInput,
  type SignInWithSessionResult,
  type SignUpWithEmailPasswordInput,
  signInWithEmailPassword,
  signUpWithEmailPassword,
  UnauthorizedError,
  verifySession,
  WeakPasswordError,
} from "./identity";
export {
  buildImportCandidate,
  buildImportJobId,
  type ExecutedImportRow,
  type ExecuteImportDependencies,
  type ExecuteImportInput,
  type ExecuteImportResult,
  executeImport,
  ImportFileError,
  type ImportRowStatus,
  importInstitutionId,
  isImportFileError,
  normalizeInstitutionImportRows,
  type ParsedImportFile,
  type ParseImportFileInput,
  type PreviewImportInput,
  type PreviewImportResult,
  parseCsvTable,
  parseImportFile,
  previewImport,
  type ValidatedImportRow,
  type ValidateImportDependencies,
  type ValidateImportInput,
  validateImport,
} from "./institution-import";
export type {
  CalculateInstitutionQualityInput,
  CalculateInstitutionQualityResult,
} from "./institution-quality";
export { calculateInstitutionQuality } from "./institution-quality";
export {
  type GetInstitutionReviewQueueDependencies,
  type GetInstitutionReviewQueueInput,
  getInstitutionReviewQueue,
  type InstitutionReviewQueue,
  isReviewAction,
  isReviewValidationError,
  REVIEW_ACTIONS,
  REVIEW_QUEUE_IDS,
  type ReviewAction,
  type ReviewCountBucket,
  type ReviewInstitutionDependencies,
  type ReviewInstitutionInput,
  type ReviewInstitutionResult,
  type ReviewQualityBand,
  type ReviewQueueFilters,
  type ReviewQueueId,
  type ReviewQueueRow,
  type ReviewSort,
  ReviewValidationError,
  reviewInstitution,
  reviewQualityBand,
} from "./institution-review";
export {
  type CreateInstitutionFiltersInput,
  type CreateInstitutionPageInput,
  type CreateInstitutionSearchQueryInput,
  type CreateInstitutionSearchResultInput,
  createInstitutionFilters,
  createInstitutionPage,
  createInstitutionSearchQuery,
  createInstitutionSearchResult,
  DEFAULT_INSTITUTION_PAGE_SIZE,
  DuplicateInstitutionError,
  type InstitutionFilters,
  type InstitutionListOptions,
  InstitutionNotFoundError,
  type InstitutionPage,
  InstitutionProfileValidationError,
  type InstitutionRepository,
  type InstitutionSearchQuery,
  type InstitutionSearchRepository,
  type InstitutionSearchResult,
  InstitutionSort,
  isDuplicateInstitutionError,
  isInstitutionNotFoundError,
  isInstitutionProfileValidationError,
  isInstitutionSort,
  parseInstitutionSort,
} from "./institutions";
export {
  isLeadNotFoundError,
  isLeadRateLimited,
  isLeadRateLimitedError,
  isLeadSpamRejectedError,
  isLeadSpamSubmission,
  isLeadValidationError,
  LeadInstitutionNotFoundError,
  LeadNotFoundError,
  type LeadNotificationRecipient,
  LeadRateLimitedError,
  type LeadRepository,
  LeadSpamRejectedError,
  LeadValidationError,
  type SubmitLeadDependencies,
  type SubmitLeadInput,
  type SubmitLeadResult,
  submitLead,
  type UpdateLeadStatusDependencies,
  type UpdateLeadStatusInput,
  type UpdateLeadStatusResult,
  updateLeadStatus,
} from "./leads";
export {
  createInstitutionMediaRepository,
  type DeleteInstitutionMediaDependencies,
  type DeleteInstitutionMediaInput,
  DuplicateMediaError,
  deleteInstitutionMedia,
  getInstitutionMediaSnapshot,
  type InstitutionMediaRepository,
  type InstitutionMediaSnapshot,
  isDuplicateMediaError,
  isMediaNotFoundError,
  isMediaValidationError,
  type ListInstitutionMediaDependencies,
  type ListInstitutionMediaInput,
  listInstitutionMedia,
  MediaNotFoundError,
  type MediaRepository,
  MediaValidationError,
  type ObjectStorage,
  type ObjectStoragePutInput,
  type ObjectStoragePutResult,
  type ReorderInstitutionMediaDependencies,
  type ReorderInstitutionMediaInput,
  rebuildMediaAsset,
  reorderInstitutionMedia,
  type SetPrimaryInstitutionMediaDependencies,
  type SetPrimaryInstitutionMediaInput,
  setPrimaryInstitutionMedia,
  syncInstitutionMediaUrls,
  type UploadInstitutionMediaDependencies,
  type UploadInstitutionMediaInput,
  uploadInstitutionMedia,
} from "./media";
export {
  emptyHomepageVisualsFallback,
  getHomepageVisuals,
  type GetHomepageVisualsDependencies,
  type HomepageVisualsRepository,
  HomepageVisualValidationError,
  isHomepageVisualValidationError,
  type UpdateHomepageVisualDependencies,
  type UpdateHomepageVisualInput,
  updateHomepageVisual,
} from "./site";
export {
  type BillingPlanRepository,
  defaultFreePlan,
  type InstitutionBillingAccess,
  type InstitutionSubscriptionRepository,
  ownerLeadUpgradeMessage,
  type PresentedOwnerLead,
  presentOwnerLeads,
  type ResolveInstitutionBillingAccessDependencies,
  resolveInstitutionBillingAccess,
} from "./billing";
export {
  buildNotificationCopy,
  ConsoleEmailService,
  createConsoleEmailService,
  createInMemoryClaimInviteEmailRateLimitStore,
  createInMemoryMailDeliveryLogRepository,
  createInMemoryNotificationRepository,
  createNotificationService,
  EDUATLAS_MAIL_FROM_DEFAULT,
  type EmailService,
  type EmailTemplateModel,
  type EmitNotificationInput,
  type EmitNotificationResult,
  emitClaimApproved,
  emitClaimSubmitted,
  emitEmailVerification,
  emitLeadReceived,
  emitPasswordReset,
  emitProfileUpdated,
  emitWelcome,
  hashClaimInviteToken,
  InMemoryClaimInviteEmailRateLimitStore,
  InMemoryMailDeliveryLogRepository,
  InMemoryNotificationRepository,
  type ClaimInviteEmailRateLimitStore,
  type ListNotificationsOptions,
  type MailDeliveryLogRepository,
  type NotificationCopy,
  type NotificationEventPayload,
  type NotificationRepository,
  NotificationService,
  type NotificationServiceDependencies,
  type RenderedEmail,
  renderEmailTemplate,
  renderNotificationEmail,
  type SendEmailInput,
  type SendEmailResult,
  type SendInstitutionClaimInviteEmailDependencies,
  type SendInstitutionClaimInviteEmailInput,
  type SendInstitutionClaimInviteEmailResult,
  sendInstitutionClaimInviteEmail,
  CLAIM_INVITE_RATE_LIMIT_MS,
  CLAIM_INVITE_TOKEN_TTL_MS,
} from "./notifications";
export {
  buildLeadConversionFunnel,
  buildLeadStatusDistribution,
  buildOwnerLeadSummary,
  type CalculateInstitutionProfileCompletenessDependencies,
  type CalculateInstitutionProfileCompletenessInput,
  calculateInstitutionProfileCompleteness,
  computeInstitutionProfileCompleteness,
  countLeadsInWindow,
  createAverageResponseTimePlaceholder,
  createGrowthTrendPlaceholder,
  createOwnerLeadTrendPlaceholder,
  createOwnerProfileCompletenessPanel,
  createOwnerRecommendationsPanel,
  createTopLeadSourcePlaceholder,
  type EvaluateOwnerRecommendationRulesInput,
  evaluateOwnerRecommendationRules,
  type GetOwnerDashboardDependencies,
  type GetOwnerDashboardInput,
  type GetOwnerInsightsDependencies,
  type GetOwnerInsightsInput,
  type GetOwnerInstitutionProfileDependencies,
  type GetOwnerInstitutionProfileInput,
  type GetOwnerLeadPipelineDependencies,
  type GetOwnerLeadPipelineInput,
  type GetOwnerRecommendationsDependencies,
  type GetOwnerRecommendationsInput,
  type GetOwnerRecommendationsResult,
  generateOwnerBusinessInsights,
  getOwnerDashboard,
  getOwnerInsights,
  getOwnerInstitutionProfile,
  getOwnerLeadPipeline,
  getOwnerRecommendations,
  type OwnerBusinessInsight,
  type OwnerDashboard,
  type OwnerInsights,
  type OwnerInsightsDistributionItem,
  type OwnerInsightsFunnelStep,
  type OwnerInsightsMetric,
  type OwnerInstitutionSummary,
  type OwnerLeadPipeline,
  type OwnerLeadPipelineColumn,
  type OwnerLeadSummary,
  type OwnerLeadTrendPlaceholder,
  type OwnerProfileCompletenessPanel,
  type OwnerProfileCompletenessSectionPanel,
  type OwnerRecommendationsPanel,
  type ProfileCompletenessResult,
  selectLeadsByStatus,
  selectRecentLeads,
  type AppendInstitutionGalleryImagesDependencies,
  type AppendInstitutionGalleryImagesInput,
  appendInstitutionGalleryImages,
  type RemoveInstitutionGalleryImageDependencies,
  type RemoveInstitutionGalleryImageInput,
  removeInstitutionGalleryImage,
  type ReorderInstitutionGalleryImagesDependencies,
  type ReorderInstitutionGalleryImagesInput,
  reorderInstitutionGalleryImages,
  type UpdateInstitutionCoverDependencies,
  type UpdateInstitutionCoverInput,
  type UpdateInstitutionBrochureDependencies,
  type UpdateInstitutionBrochureInput,
  type RemoveInstitutionBrochureDependencies,
  type RemoveInstitutionBrochureInput,
  type UpdateInstitutionLogoDependencies,
  type UpdateInstitutionLogoInput,
  type UpdateInstitutionProfileDependencies,
  type UpdateInstitutionProfileInput,
  type UpdateInstitutionProfileResult,
  updateInstitutionCover,
  updateInstitutionBrochure,
  removeInstitutionBrochure,
  updateInstitutionLogo,
  updateInstitutionProfile,
} from "./owner";
